spring:
  application:
    name: gateway-service
  config:
    import: "configserver:"
  cloud:
    gateway:
      routes:
        - id: incident-service
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/api/incidents/**