-- 1. TABLE CREATION 

-- Teams table 
CREATE TABLE constructors (
    id_team NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    principal VARCHAR2(50),
    base_city VARCHAR2(50),
    budget_cap NUMBER(15, 2) CHECK (budget_cap > 0) -- Budget need to be positive
);

-- Drivers table
CREATE TABLE drivers (
    id_driver NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(50) NOT NULL,
    driver_number NUMBER UNIQUE CHECK (driver_number > 0 AND driver_number < 100), -- cant be more then 100
    country VARCHAR2(3),
    id_team NUMBER,
    CONSTRAINT fk_team FOREIGN KEY (id_team) 
        REFERENCES constructors(id_team) 
        ON DELETE SET NULL -- if team gone driver has no team
);

-- Races table 
CREATE TABLE races (
    id_race NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gp_name VARCHAR2(100) NOT NULL,
    circuit VARCHAR2(100),
    race_date DATE DEFAULT SYSDATE,
    laps NUMBER CHECK (laps > 0)
);

-- Race results 
CREATE TABLE race_results (
    id_result NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_race NUMBER NOT NULL REFERENCES races(id_race) ON DELETE CASCADE,
    id_driver NUMBER NOT NULL REFERENCES drivers(id_driver) ON DELETE CASCADE,
    position NUMBER CHECK (position BETWEEN 1 AND 20),
    points NUMBER(4,1) DEFAULT 0.0,
    fastest_lap CHAR(1) DEFAULT 'N' CHECK (fastest_lap IN ('Y', 'N')), -- Y has the fastest lap
    UNIQUE(id_race, id_driver) -- driver can complete race once
);

-- 2. DATA INSERTION  

-- Add 2024 teams
INSERT INTO constructors (name, principal, base_city, budget_cap) VALUES ('Red Bull Racing', 'Christian Horner', 'Milton Keynes', 145000000);
INSERT INTO constructors (name, principal, base_city, budget_cap) VALUES ('Ferrari', 'Fred Vasseur', 'Maranello', 145000000);
INSERT INTO constructors (name, principal, base_city, budget_cap) VALUES ('McLaren', 'Andrea Stella', 'Woking', 140000000);

-- Add drivers
INSERT INTO drivers (full_name, driver_number, country, id_team) VALUES ('Max Verstappen', 1, 'NED', 1);
INSERT INTO drivers (full_name, driver_number, country, id_team) VALUES ('Charles Leclerc', 16, 'MON', 2);
INSERT INTO drivers (full_name, driver_number, country, id_team) VALUES ('Lando Norris', 4, 'GBR', 3);
INSERT INTO drivers (full_name, driver_number, country, id_team) VALUES ('Carlos Sainz', 55, 'ESP', 2);

-- Add Bahrain GP
INSERT INTO races (gp_name, circuit, laps) VALUES ('Bahrain Grand Prix', 'Sakhir', 57);

-- results for 
INSERT INTO race_results (id_race, id_driver, position, points, fastest_lap) VALUES (1, 1, 1, 26, 'Y'); -- verstappen fastest (2026 predictions)
INSERT INTO race_results (id_race, id_driver, position, points, fastest_lap) VALUES (1, 2, 2, 18, 'N'); -- next year is ferrari's year
COMMIT;

-- 3. PL/SQL 

-- Procedure for driver transfer 
CREATE OR REPLACE PROCEDURE transfer_driver(
    p_driver_number IN NUMBER,
    p_new_team_name IN VARCHAR2
) AS
    v_new_team_id NUMBER;
BEGIN
    -- Find new team ID
    SELECT id_team INTO v_new_team_id 
    FROM constructors 
    WHERE name = p_new_team_name;

    -- Update driver
    UPDATE drivers 
    SET id_team = v_new_team_id 
    WHERE driver_number = p_driver_number;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Success: Driver is' || p_driver_number || ' transferred.');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Error team is not found.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error while transfer.');
END;
/

-- 4. PROJECT TEST

SET SERVEROUTPUT ON;
DECLARE
    v_points NUMBER;
BEGIN
    -- Create Williams for test
    INSERT INTO constructors (name, principal, base_city, budget_cap) VALUES ('Williams', 'James Vowles', 'Grove', 135000000);
    COMMIT;
    
    -- Test: Transfer Sainz (55) to Williams
    transfer_driver(55, 'Williams');

END;
/